intent_data = [("Bonsoir djom", {"entities": [], "intent": "discussion"}),
("Je veux une orientation professionnelle ", {"entities": [], "intent": "recherche_emploi"}),
("C’est qui Semiat Olaitan", {"entities": [], "intent": "hors_contexte"}),
("J’ai eu un bac scientifique avec 15.45 comme moyenne et je veux m’orienter vers les sciences et ingénieries, tu me conseilles quoi comme formation et université ?", {"entities": [("bac scientifique", "NIVEAU"), ("15.45", "NOTE"), ("sciences", "DOMAINE"), ("ingénieries", "DOMAINE")], "intent": "recherche_formation"}),
("Bonjour Djom comment ça va?", {"entities": [], "intent": "discussion"}),
("Je veux savoir comment devenir un grand codeur", {"entities": [], "intent": "recherche_info"}),
("D'accord. Quelles écoles proposent des formations en développement web et mobile ?", {"entities": [("développement web et mobile", "DOMAINE")], "intent": "recherche_ecole"}),
("C'est quoi L'Université du Togo?", {"entities": [("Togo", "LOC")], "intent": "recherche_ecole"}),
("ok Comment intégrer l'epl?", {"entities": [("epl", "ECOLE")], "intent": "info_admission"}),
("Je parle de l'école polytechnique de Lomé", {"entities": [("école polytechnique de Lomé", "ECOLE"), ("Lomé", "LOC")], "intent": "recherche_ecole"}),
("C'est sur concours?", {"entities": [], "intent": "info_admission"}),
("D'accord", {"entities": [], "intent": "discussion"}),
("Que me proposes tu?", {"entities": [], "intent": "recherche_info"}),
("Je suis bachelier et je suis fasciné par le developpement d'applications et les ordinateurs?", {"entities": [("bac", "NIVEAU"), ("developpement d'applications", "DOMAINE")], "intent": "recherche_formation"}),
("fait moi la liste de ces formations", {"entities": [], "intent": "recherche_formation"}),
("C'est quoi le Macrame?", {"entities": [("Macrame", "DOMAINE")], "intent": "hors_contexte"}),
("En quoi a t-il rapport avec l'informatique?", {"entities": [("informatique", "DOMAINE")], "intent": "clarification"}),
("Et l'IAI?", {"entities": [("IAI", "ECOLE")], "intent": "recherche_ecole"}),
("IAI Togo", {"entities": [("IAI Togo", "ECOLE"), ("Togo", "LOC")], "intent": "recherche_ecole"}),
("Quoi faire de mes chaussures", {"entities": [], "intent": "hors_contexte"}),
("Et si je veux mourir?", {"entities": [], "intent": "non_ethique"}),
("Je peux faire un faux malade pour ne pas aller à l'école?", {"entities": [], "intent": "non_ethique"}),
("Ok quelle modele de voiture me proposes tu?", {"entities": [], "intent": "hors_contexte"}),
("je peux utiliser la voiture pour étudier non", {"entities": [], "intent": "hors_contexte"}),
("Aide moi à creer fibre optique", {"entities": [("fibre optique", "DOMAINE")], "intent": "hors_contexte"}),
("Non je veux que tu me montre les étapes à suivre pour produire ces cables", {"entities": [], "intent": "hors_contexte"}),
("D'accord", {"entities": [], "intent": "discussion"}),
("Je ne veux plus poursuivre", {"entities": [], "intent": "info"}),
("oui aide moi. J'apprends vite et j'aime me former", {"entities": [], "intent": "info"}),
("je veux diriger les gens dans l'entreprise", {"entities": [], "intent": "recherche_emploi"}),
("J'ai fait la C4. Je suis en Tle. Je viens d'avoir le BAC. Qu'est-ce que tu me proposes de faire?", {"entities": [("C4", "DOMAINE"), ("Tle", "NIVEAU"),  ("BAC", "NIVEAU")], "intent": "recherche_formation"}),
("Ok quelles écoles proposes ça ? ", {"entities": [], "intent": "recherche_ecole"}),
("Tu es sûr que l'ESP existe au Togo ?", {"entities": [("Togo", "LOC")], "intent": "recherche_ecole"}),
("Je suis bachelier et je suis fasciné par le developpement d'applications et les ordinateurs?", {"entities": [("developpement d'applications", "DOMAINE")], "intent": "info"}),
("Bonjour je suis en terminale scientifique. Que puis-je faire comme études ?", {"entities": [("terminale", "NIVEAU")], "intent": "recherche_formation"}),
("pas vraiment, fais moi des propositions", {"entities": [], "intent": "recherche_formation"}),
("et si je ne souhaite plus étudier ?", {"entities": [], "intent": "info"}),
("je n'ai pas assez d'argent pour l'instant donc je veux faire de petits jobs pendant un an avant de reprendre les études. Que me conseille tu?", {"entities": [], "intent": "recherche_emploi"}),
("couture ou tresse ou aide maçon", {"entities": [ ("couture", "DOMAINE"), ("tresse", "DOMAINE"), ("aide maçon", "DOMAINE")], "intent": "comparaison"}),
("ok où puis je apprendre la couture?", {"entities": [("couture", "DOMAINE")], "intent": "recherche_ecole"}),
("Quel sont les centres de formation ?", {"entities": [], "intent": "recherche_ecole"}),
("Bonsoir Djom", {"entities": [], "intent": "discussion"}),
("je viens d'obtenir mon bac D et je suis intéressé par la Sécurité et Santé au Travail", {"entities": [("bac", "NIVEAU"), ("D", "DOMAINE"), ("Sécurité et Santé au Travail", "DOMAINE")], "intent": "info"}),
("Il n' y a pas d'autres institut à lomé qui offrent ça?", {"entities": [("lomé", "LOC")], "intent": "recherche_ecole"}),
("où se trouve l'ISTES", {"entities": [("ISTES", "ECOLE")], "intent": "recherche_ecole"}),
("parle moi de l'IFOMESS", {"entities": [("IFOMESS", "ECOLE")], "intent": "recherche_info"}),
("quelles autres formations offrent ils?", {"entities": [], "intent": "recherche_formation"}),
("Je peux me former en sécurité et santé au travail à esgis ou Ucao?", {"entities": [("sécurité et santé au travail", "DOMAINE"), ("esgis", "ECOLE"), ("Ucao", "ECOLE")], "intent": "comparaison"}),
("Quel est le coût de cette formation à IFOMESS?", {"entities": [("IFOMESS", "ECOLE")], "intent": "info_cout"}),
("Et les conditions d'accès?", {"entities": [], "intent": "info_admission"}),
("Salut j’aime les maths et je voudrais choisir une filière à l’université ", {"entities": [("maths", "DOMAINE")], "intent": "recherche_formation"}),
("Tu as des noms d’universités ?", {"entities": [], "intent": "recherche_ecole"}),
("Il n'y a que deux universités publiques au Togo", {"entities": [("Togo", "LOC")], "intent": "info"}),
("A par ces deux universités, il n'y a pas d'autres qui proposent des formations en maths?", {"entities": [("maths", "DOMAINE")], "intent": "recherche_ecole"}),
("Je veux démarrer la première année d’université ", {"entities": [], "intent": "info_admission"}),
("hi you speack english", {"entities": [], "intent": "discussion"}),
("programme de 3ime", {"entities": [], "intent": "recherche_info"}),
("SYMPTOME DU PALUDISME", {"entities": [], "intent": "hors_contexte"}),
("LA LANGE LA MOINS CELEBRE AU MONDE", {"entities": [], "intent": "hors_contexte"}),
("JE SUIS EN TERMINALE ", {"entities": [("TERMINALE", "NIVEAU")], "intent": "info"}),
("ces informations ne sont pas totalement exact", {"entities": [], "intent": "info"}),
("J'AIME BIEN LE FOOTBALL ", {"entities": [("FOOTBALL", "DOMAINE")], "intent": "info"}),
("JE SUIS EN CLASSE DE 4eme ", {"entities": [("4eme", "NIVEAU")], "intent": "info"}),
("J'AIMERAIS TRAVAILLER a LOME CONTENAIR TERMINALE S.A", {"entities": [("LOME CONTENAIR TERMINALE S.A", "ENT")], "intent": "recherche_entreprise"}),
("JE SUIS EN 4eme ", {"entities": [("4eme", "NIVEAU")], "intent": "info"}),
("J'AIMERAIS FAIRE LA GESTION", {"entities": [("GESTION", "DOMAINE")], "intent": "recherche_emploi"}),
("la gestion financière", {"entities": [("gestion financière", "FILIERE")], "intent": "discussion"}),
("Je ne fais pas la série F4. En classe de 4em, il n'y a pas de séries", {"entities": [("F4", "FILIERE"), ("4em", "NIVEAU")], "intent": "info"}),
("J'AIMERAIS FAIRE LA GESTION", {"entities": [("GESTION", "DOMAINE")], "intent": "recherche_formation"}),
("Je suis en 2eme année de  géographie", {"entities": [("2eme année", "NIVEAU"), ("géographie", "FILIERE")], "intent": "info"}),
("C'est super alors. Quel etablissement choisir entre Formatec et l'univ de Kara", {"entities": [("Formatec", "ECOLE"), ("univ de Kara", "ECOLE"), ("Kara", "LOC")], "intent": "comparaison"}),
("Je penses que je vais choisir le formatec", {"entities": [("formatec", "ECOLE")], "intent": "info"}),
("Merci pour le conseil", {"entities": [], "intent": "discussion"}),
("BRO POSE MOI DES QUESTION ", {"entities": [], "intent": "discussion"}),
("POUR DEVELOPPER MA COMPÉTENCE APRES MON BEPC JE VAIS FAIRE LE G2?", {"entities": [("BEPC", "NIVEAU"), ("G2", "FILIERE")], "intent": "recherche_formation"}),
("Je ne comprends rien", {"entities": [], "intent": "clarification"}),
("doctorat, ça dure combien d'année", {"entities": [("doctorat", "NIVEAU")], "intent": "info_duree"}),
("combien d'années totale on dure á l'université ", {"entities": [], "intent": "info_duree"}),
("A quel âge un humain normal peut mourir", {"entities": [], "intent": "hors_contexte"}),
("quel metier me convient", {"entities": [], "intent": "recherche_emploi"}),
("la technologie", {"entities": [("technologie", "DOMAINE")], "intent": "discussion"}),
("Je préfère le réseau informatique", {"entities": [("réseau informatique", "DOMAINE")], "intent": "info"}),
("D'accord", {"entities": [], "intent": "discussion"}),
("Ok je comprends", {"entities": [], "intent": "discussion"}),
("Bye", {"entities": [], "intent": "discussion"}),
("je veux faire l'achitecture", {"entities": [("achitecture", "DOMAINE")], "intent": "recherche_formation"}),
("Quel est l'intéret des sciences sociales en architecture?", {"entities": [("sciences sociales", "DOMAINE"), ("architecture", "DOMAINE")], "intent": "recherche_info"}),
("Super et si je veux entreprendre?", {"entities": [], "intent": "recherche_emploi"}),
("Donne moi des idées d'entreprises", {"entities": [], "intent": "recherche_entreprise"}),
("Quels sont les defis auxquels le togo fait face et que l'architecture peut résoudre?", {"entities": [("togo", "LOC"), ("architecture", "DOMAINE")], "intent": "recherche_info"}),
("Bonjour Djom", {"entities": [], "intent": "discussion"}),
("Non je viens d'obtenir mon Bac D mais je ne sais quoi faire", {"entities": [("Bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_formation"}),
("Je ne sais pas encore", {"entities": [], "intent": "discussion"}),
("je n'ai plus envie d'étudier je veux travailler", {"entities": [], "intent": "recherche_emploi"}),
("j'ai des compétneces en bureautique", {"entities": [("bureautique", "COMPETENCE")], "intent": "info"}),
("Ok je choisi d'être Assistant de direction", {"entities": [("Assistant de direction", "DOMAINE")], "intent": "recherche_emploi"}),
("je vais suivre une formation en gestion de la relation client", {"entities": [("gestion de la relation client", "FILIERE")], "intent": "recherche_formation"}),
("Je ne sais pas encore", {"entities": [], "intent": "discussion"}),
("donne moi des raisons pour choisir l' esgis ou Ucao?", {"entities": [("esgis", "ECOLE"), ("Ucao", "ECOLE")], "intent": "comparaison"}),
("Je parle d'ESGIS et non. L'UCAO ne forme pas en santé", {"entities": [("ESGIS", "ECOLE"), ("UCAO", "ECOLE")], "intent": "clarification"}),
("C’est quoi un assistant de direction et que fait-il ?", {"entities": [("assistant de direction", "DOMAINE")], "intent": "recherche_emploi"}),
("Quel est le plus grand océan du monde ?", {"entities": [], "intent": "hors_contexte"}),
("Quelles formations courtes me permettent de travailler rapidement dans le domaine informatique ?", {"entities": [("informatique", "DOMAINE")], "intent": "recherche_formation"}),
("D'accord", {"entities": [], "intent": "discussion"}),
("Je m’intéresse à l’IA et au Big Data, quelles écoles au Togo proposent ces filières ?", {"entities": [("IA", "DOMAINE"), ("Big Data", "DOMAINE"), ("Togo", "LOC")], "intent": "recherche_ecole"}),
("Quel est le salaire moyen d’un ingénieur en cybersécurité au Togo ?", {"entities": [("ingénieur", "NIVEAU"), ("cybersécurité", "FILIERE"), ("Togo", "LOC")], "intent": "info_salaire"}),
("où se trouve une école d’ingénieur", {"entities": [("ingénieur", "NIVEAU")], "intent": "recherche_ecole"}),
("Quels programmes existent pour se former en cybersécurité sans passer par l’université", {"entities": [("cybersécurité", "DOMAINE")], "intent": "recherche_formation"}),
("Je souhaite devenir entrepreneur tech, quelles formations sont adaptées", {"entities": [], "intent": "recherche_formation"}),
("Combien de temps dure un master en Big Data à l’Université de Kara ?", {"entities": [("Big Data", "DOMAINE"), ("Université de Kara", "ECOLE")], "intent": "info_duree"}),
("Je veux travailler dans l’informatique, quels métiers puis-je exercer sans diplôme universitaire ?", {"entities": [("informatique", "DOMAINE")], "intent": "recherche_emploi"}),
("Quels jobs offrent le plus d’expérience pratique pour un débutant ?", {"entities": [], "intent": "recherche_emploi"}),
("Je veux travailler dans l’énergie renouvelable, quels diplômes suivre ?", {"entities": [("énergie renouvelable", "DOMAINE")], "intent": "recherche_formation"}),
("Est-ce que la formation en sécurité et santé au travail est reconnue par l’État ?", {"entities": [("sécurité et santé au travail", "DOMAINE")], "intent": "recherche_info"}),
("Quels documents dois-je fournir pour m’inscrire à l’IFOMESS ?", {"entities": [("IFOMESS", "ECOLE")], "intent": "info_admission"}),
("Les formations en développement web sont-elles disponibles en ligne au Togo ?", {"entities": [("développement web", "DOMAINE"), ("Togo", "LOC")], "intent": "recherche_formation"}),
("Je cherche un travail à temps partiel pendant mes études, quelles options existent ?", {"entities": [], "intent": "recherche_emploi"}),
("Quels emplois sont accessibles avec un bac D ?", {"entities": [("bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_emploi"}),
("Quelle est la différence entre BTS et DUT en gestion ?", {"entities": [("BTS", "NIVEAU"), ("DUT", "NIVEAU"), ("gestion", "DOMAINE")], "intent": "comparaison"}),
("explique-moi le BTS", {"entities": [("BTS", "NIVEAU")], "intent": "recherche_info"}),
("Peux-tu me dire la recette d’un gâteau au chocolat ?", {"entities": [], "intent": "hors_contexte"}),
("Je viens d'obtenir mon bac scientifique", {"entities": [("bac", "NIVEAU"), ("scientifique", "FILIERE")], "intent": "info"}),
("je veux faire du big data", {"entities": [("big data", "DOMAINE")], "intent": "recherche_formation"}),
("Où puis je faire cette licence?", {"entities": [("licence", "NIVEAU")], "intent": "recherche_ecole"}),
("Combien ça put me couter?", {"entities": [], "intent": "info_cout"}),
("Que propose concrètement l'UL?", {"entities": [("UL", "ECOLE")], "intent": "recherche_ecole"}),
("Bonjour je suis en terminale scientifique. Que puis-je faire comme études ?", {"entities": [("bac", "NIVEAU"), ("scientifique", "FILIERE")], "intent": "recherche_formation" }),
("pas vraiment, fais moi des propositions", {"entities": [], "intent": "discussion" }),
("et si je ne souhaite plus étudier ?", {"entities": [], "intent": "discussion" }),
("je n'ai pas assez d'argent pour l'instant donc je veux faire de petis jobs pendant un an avant de reprendre les études. Que me conseille tu?", {"entities": [], "intent": "recherche_emploi"}),
("couture ou tresse ou aide maçon", {"entities": [("couture", "DOMAINE"), ("tresse", "DOMAINE"), ("aide maçon", "DOMAINE")], "intent": "comparaison" }),
("je t'ai déjà dit que je veux faire de la couture ou tresse ou l'aide maçon", {"entities": [("couture", "DOMAINE"), ("tresse", "DOMAINE"), ("aide maçon", "DOMAINE")], "intent": "clarification" }),
("ok où puis je apprendre la couture?", {"entities": [("couture", "DOMAINE")], "intent": "recherche_ecole" }),
("Quel sont les centres de formation ?", {"entities": [], "intent": "recherche_ecole" }),
("cite moi ces centres de formation", {"entities": [], "intent": "recherche_ecole" }),
("je veux une liste", {"entities": [], "intent": "discussion" }),
("Je viens d'avoir mon bac littéraire mais je ne sais vers quoi me diriger à l'université", {"entities": [("bac", "NIVEAU"), ("littéraire", "FILIERE")], "intent": "recherche_formation" }),
("langue, art oratoire", {"entities": [("langue", "COMPETENCE"), ("", "art oratoire")], "intent": "info" }),
("c'est quoi la philologie ?", {"entities": [("philologie", "DOMAINE")], "intent": "recherche_info" }),
("cette option est elle disponible au togo?", {"entities": [("togo", "LOC")], "intent": "recherche_info" }),
("oui", {"entities": [], "intent": "discussion" }),
("je suis interesé par le droit", {"entities": [("droit", "DOMAINE")], "intent": "info" }),
("quels sont les sources que tu as utilisé pour répondre?", {"entities": [], "intent": "recherche_info" }),
("Bonjour Djom", {"entities": [], "intent": "discussion" }),
("Non je viens d'obtenir mon Bac D mais je ne sais quoi faire", {"entities": [("Bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_formation" }),
("je n'ai plus envie d'étudier je veux travailler", {"entities": [], "intent": "recherche_emploi"}),
("j'ai des compétneces en bureautique", {"entities": [("bureautique", "COMPETENCE")], "intent": "info"}),
("Ok je choisi d'être Assistant de direction", {"entities": [("Assistant de direction", "DOMAINE")], "intent": "recherche_emploi"}),
("Waoo c'est intéressant donne moi plus d'info sur CIN INTA SOKODE", {"entities": [("CIN INTA SOKODE", "ECOLE")], "intent": "recherche_info" }),
("et si je veux mz former à la sécurité, santé au travail?", {"entities": [("sécurité, santé au travail", "FILIERE")], "intent": "recherche_formation" }),
("où trouver cette formation?", {"entities": [], "intent": "recherche_ecole" }),
("Et l'IFOMESS?", {"entities": [("IFOMESS", "ECOLE")], "intent": "recherche_info" }),
("les instituts qui forment en Sécurité et la Santé au Travail", {"entities": [("Sécurité et la Santé au Travail", "FILIERE")], "intent": "recherche_ecole" }),
("Bonsoir Djom", {"entities": [], "intent": "discussion" }),
("je viens d'obtenir mon bac D et je suis intéressé par la Sécurité et Santé au Travail", {"entities": [("bac", "NIVEAU"), ("D", "FILIERE"), ("Sécurité et Santé au Travail", "FILIERE")], "intent": "info" }),
("Où puis je me former à ça?", {"entities": [], "intent": "recherche_ecole" }),
("Il n' y a pas d'autres institut à lomé aui offrent ça?", {"entities": [], "intent": "recherche_ecole" }),
("Connais tu ifomess?", {"entities": [("ifomess", "ECOLE")], "intent": "recherche_info" }),
("quelles autres formations offrent ils?", {"entities": [], "intent": "recherche_info" }),
("D'accord. merci", {"entities": [], "intent": "discussion" }),
("Et esgis ou Ucao?", {"entities": [("esgis", "ECOLE"), ("Ucao", "ECOLE")], "intent": "recherche_info" }),
("c'est vrai ça?", {"entities": [], "intent": "clarification" }),
("Salut j’aime les maths et je voudrais choisir une filière à l’université ", {"entities": [("maths", "DOMAINE")], "intent": "recherche_formation" }),
("Tu as des noms d’universités ?", {"entities": [], "intent": "recherche_ecole" }),
("Je veux une université ou école qui allie pratique et theorie", {"entities": [], "intent": "recherche_ecole" }),
("Je veux démarrer la première année d’université ", {"entities": [("première année", "NIVEAU")], "intent": "recherche_formation" }),
("hi you speack english", {"entities": [], "intent": "discussion"}),
("programme de 3ime", {"entities": [], "intent": "recherche_info"}),
("SYMPTOME DU PALUDISME", {"entities": [], "intent": "hors_contexte"}),
("LA LANGE LA MOINS CELEBRE AU MONDE", {"entities": [], "intent": "hors_contexte"}),
("JE SUIS EN TERMINALE ", {"entities": [("TERMINALE", "NIVEAU")], "intent": "info"}),
("ces informations ne sont pas totalement exact", {"entities": [], "intent": "clarification"}),
("J'AIME BIEN LE FOOTBALL ", {"entities": [("FOOTBALL", "DOMAINE")], "intent": "info"}),
("JE SUIS EN CLASSE DE 4eme ", {"entities": [("4eme", "NIVEAU")], "intent": "info"}),
("J'AIMERAIS TRAVAILLER a LOME CONTENAIR TERMINALE S.A", {"entities": [("LOME CONTENAIR TERMINALE S.A", "ENT")], "intent": "recherche_entreprise"}),
("JE SUIS EN 4eme ", {"entities": [("4eme", "NIVEAU")], "intent": "info"}),
("J'AIMERAIS FAIRE LA GESTION", {"entities": [("GESTION", "DOMAINE")], "intent": "recherche_emploi"}),
("BRO POSE MOI DES QUESTION ", {"entities": [], "intent": "discussion" }),
("LA GESTION FINANCIERE", {"entities": [("GESTION FINANCIERE", "FILIERE")], "intent": "recherche_info" }),
("POUR DEVELOPPER MA COMPÉTENCE APRES MON BEPC JE VAIS FAIRE LE G2", {"entities": [("BEPC", "NIVEAU"),("G2", "FILIERE")], "intent": "recherche_formation" }),
("doctora ça dure combien d'année", {"entities": [], "intent": "info_duree" }),
("combien d'années totale on dure á l'université ", {"entities": [], "intent": "info_duree" }),
("A quel âge un humain normal peut mourir", {"entities": [], "intent": "hors_contexte" }),
("quel metier me convient", {"entities": [], "intent": "recherche_emploi" }),
("je suis en classe de terminale D", {"entities": [("terminal", "NIVEAU"), ("D", "FILIERE")], "intent": "info" }),
("technologie", {"entities": [("technologie", "DOMAINE")], "intent": "discussion" }),
("la technologie", {"entities": [("technologie", "DOMAINE")], "intent": "discussion" }),
("je veux faire l achitecture", {"entities": [("achitecture", "DOMAINE")], "intent": "recherche_formation" }),
("ingeniere", {"entities": [("ingeniere", "DOMAINE")], "intent": "info" }),
("Ingénierie électrique ", {"entities": [("Ingénierie électrique", "DOMAINE")], "intent": "info" }),
("ok texte mon niveau", {"entities": [], "intent": "discussion" }),
("nn", {"entities": [], "intent": "discussion" }),
("je passe en terminal", {"entities": [("terminal", "NIVEAU")], "intent": "info" }),
("je veux devenir ingenerie en electricite", {"entities": [("ingenerie", "DOMAINE"), ("electricite", "DOMAINE")], "intent": "recherche_formation" }),
("pose moi des question", {"entities": [], "intent": "discussion" }),
("1) la fabrication ", {"entities": [("fabrication", "DOMAINE")], "intent": "info" }),
("Des machines, des équipements", {"entities": [], "intent": "info" }),
("J'aime les jeux vidéo et suis sociable j'ai pas de qualité précis ", {"entities": [], "intent": "info" }),
("J'aime les jeux comme graw a garden brawl star", {"entities": [], "intent": "info" }),
("Okay vue que j'aime un peu le domaine des jeux je me suis dit je fais faire la série D etc et m'améliorer côté informatique afin de pouvoir créer la jeux ...", {"entities": [("D", "FILIERE"), ("informatique", "DOMAINE")], "intent": "info" }),
("Genre je vais vite résumé suis un élève de la classe de 4eme mais j'ai pas encore de pc ...", {"entities": [("4eme", "NIVEAU")], "intent": "info" }),
("Non 4eme collège", {"entities": [("4eme", "NIVEAU")], "intent": "info" }),
("Azy tu le le dire à peux près quel travail je peux faire avec les infos que je t'ai énumérés ", {"entities": [], "intent": "recherche_emploi" }),
("stl", {"entities": [], "intent": "discussion" }),
("les sciences", {"entities": [("science", "DOMAINE")], "intent": "recherche_info" }),
("informatique", {"entities": [("informatique", "DOMAINE")], "intent": "recherche_info" }),
("oui", {"entities": [], "intent": "discussion" }),
("connait tu autre chose", {"entities": [], "intent": "discussion" }),
("je ne comprend pas ", {"entities": [], "intent": "clarificassion" }),
("vendre des chose qui sont essentiel a nos jeune ", {"entities": [], "intent": "discussion" }),
("des produits electronique", {"entities": [], "intent": "recherche_info" }),
("des produit de haut technologie", {"entities": [], "intent": "recherche_info" }),
("par exemple des ordinateur", {"entities": [], "intent": "info" }),
("des ordinateur portable comme =moi j utilise", {"entities": [], "intent": "discussion" }),
("des ecran de haut definition", {"entities": [], "intent": "discussion" }),
("ok", {"entities": [], "intent": "discussion" }),
("Je m'appelle joseph", {"entities": [], "intent": "info" }),
("Secondaire", {"entities": [("Secondaire", "NIVEAU")], "intent": "info" }),
("Non troisième", {"entities": [("troisième", "NIVEAU")], "intent": "discussion" }),
("Comment savoir son série", {"entities": [], "intent": "recherche_info" }),
("Bonjour Djom, comment ça va ?", {"entities": [], "intent": "discussion" }),
(" Salut, peux-tu m’aider à choisir une formation ? ", {"entities": [], "intent": "recherche_formation" }),
("Bonsoir, je voudrais des conseils pour mon orientation.", {"entities": [], "intent": "recherche_formation" }),
("C’est quoi un assistant de direction et que fait-il ?", {"entities": [("assistant de direction", "DOMAINE")], "intent": "recherche_emploi"}),
("Quel est le plus grand océan du monde ?", {"entities": [], "intent": "hors_contexte"}),
("Quelles formations courtes me permettent de travailler rapidement dans le domaine informatique ?", {"entities": [("informatique", "DOMAINE")], "intent": "recherche_formation"}),
("Quels métiers peut-on exercer après un BTS en gestion ?", {"entities": [("BTS", "NIVEAU"), ("gestion ", "DOMAINE")], "intent": "recherche_emploi" }),
("Je m’intéresse à l’IA et au Big Data, quelles écoles au Togo proposent ces filières ?", {"entities": [("IA", "DOMAINE"), ("Big Data", "DOMAINE"), ("Togo", "LOC")], "intent": "recherche_ecole"}),
("Quel est le salaire moyen d’un ingénieur en cybersécurité au Togo ?", {"entities": [("ingénieur", "NIVEAU"), ("cybersécurité", "FILIERE"), ("Togo", "LOC")], "intent": "info_salaire"}),
("donne-moi des centres de formation en mécanique", {"entities": [("mécanique", "DOMAINE")], "intent": "recherche_ecole" }),
("où se trouve une école d’ingénieur", {"entities": [("ingénieur", "NIVEAU")], "intent": "recherche_ecole"}),
("je veux travailler directement", {"entities": [], "intent": "recherche_emploi" }),
("Quels programmes existent pour se former en cybersécurité sans passer par l’université", {"entities": [("cybersécurité", "DOMAINE")], "intent": "recherche_formation"}),
("Est-ce que la formation en sécurité et santé au travail est reconnue par l’État ?", {"entities": [("sécurité et santé au travail", "DOMAINE")], "intent": "recherche_info"}),
("Je souhaite devenir entrepreneur tech, quelles formations sont adaptées", {"entities": [], "intent": "recherche_formation"}),
("Quels cursus permettent de combiner art et technologie ?", {"entities": [("art", "DOMAINE"), ("technologie", "DOMAINE")], "intent": "recherche_formation" }),
("Combien de temps dure un master en Big Data à l’Université de Kara ?", {"entities": [("Big Data", "DOMAINE"), ("Université de Kara", "ECOLE")], "intent": "info_duree"}),
("Je veux travailler dans l’informatique, quels métiers puis-je exercer sans diplôme universitaire ?", {"entities": [("informatique", "DOMAINE")], "intent": "recherche_emploi"}),
("Quels jobs offrent le plus d’expérience pratique pour un débutant ?", {"entities": [], "intent": "recherche_emploi"}),
("Quels sont les critères pour entrer en licence informatique à l’Université de Lomé ?", {"entities": [("licence", "NIVEAU"), ("informatique", "DOMAINE"), ("Université de Lomé", "ECOLE")], "intent": "info_admission" }),
("Quels diplômes sont nécessaires pour travailler comme coordinateur de projet ?", {"entities": [("coordinateur de projet", "DOMAINE")], "intent": "recherche_emploi" }),
("Quels emplois combinent créativité et technologie ?", {"entities": [("créativité", "DOMAINE"), ("technologie", "DOMAINE")], "intent": "recherche_emploi" }),
("Je veux travailler dans l’énergie renouvelable, quels diplômes suivre ?", {"entities": [("énergie renouvelable", "DOMAINE")], "intent": "recherche_formation"}),
("Quels documents dois-je fournir pour m’inscrire à l’IFOMESS ?", {"entities": [("IFOMESS", "ECOLE")], "intent": "info_admission"}),
("Quels métiers permettent de travailler dans les jeux vidéo ou le développement de jeux ?", {"entities": [("développement de jeux", "DOMAINE")], "intent": "recherche_emploi" }),
("Les formations en développement web sont-elles disponibles en ligne au Togo ?", {"entities": [("développement web", "DOMAINE"), ("Togo", "LOC")], "intent": "recherche_formation"}),
("Quelles filières combinent sciences et management  ?", {"entities": [("sciences", "DOMAINE"), ("management", "DOMAINE")], "intent": "recherche_info" }),
("Peux-tu me donner les prérequis pour devenir assistant de direction ?", {"entities": [("assistant de direction", "DOMAINE")], "intent": "recherche_emploi" }),
("j’ai fait un BTS en gestion, quelles options d’emploi", {"entities": [("BTS", "NIVEAU"), ("gestion", "DOMAINE")], "intent": "recherche_emploi" }),
("Quels emplois sont accessibles avec un bac D ?", {"entities": [("bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_emploi"}),
("Quelle est la différence entre BTS et DUT en gestion ?", {"entities": [("BTS", "NIVEAU"), ("DUT", "NIVEAU"), ("gestion", "DOMAINE")], "intent": "comparaison"}),
("Quels métiers manuels sont les mieux rémunérés au Togo ?", {"entities": [("Togo", "LOC")], "intent": "info_salaire" }),
("Comment fonctionne un moteur à explosion ? ", {"entities": [], "intent": "hors_contexte" }),
("Quels emplois sont adaptés à quelqu’un avec des compétences en bureautique et informatique ?", {"entities": [("bureautique", "COMPETENCES"), ("informatique", "COMPETENCES")], "intent": "recherche_emploi" }),
("Quelles formations en santé sont accessibles avec un bac D", {"entities": [("santé", "DOMAINE"), ("bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_formation" }),
("c’est quoi le bac D", {"entities": [("bac", "NIVEAU"), ("D", "FILIERE")], "intent": "recherche_info" }),
("Je veux devenir assistant de direction, quels emplois puis-je postuler dès maintenant ?", {"entities": [("assistant de direction", "DOMAINE")], "intent": "recherche_emploi" }),
("explique-moi le BTS", {"entities": [("BTS", "NIVEAU")], "intent": "clarification" }),
("Quelles formations existent pour devenir développeur mobile ?", {"entities": [("développeur mobile", "DOMAINE")], "intent": "recherche_formation" }),
("quelles sont les conditions pour aller à l’université de Lomé", {"entities": [("université de Lomé", "ECOLE")], "intent": "info_admission" }),
("Quelles entreprises au Togo recrutent des jeunes diplômés en gestion ?", {"entities": [("Togo", "LOC"), ("gestion", "DOMAINE")], "intent": "recherche_entreprise" }),
("Existe-t-il des bourses pour étudier le droit au Togo ?", {"entities": [("droit", "DOMAINE"), ("Togo", "LOC")], "intent": "recherche_bourse" }),
("où puis-je apprendre la couture", {"entities": [("couture", "DOMAINE")], "intent": "recherche_ecole" }),
("j’ai un bac littéraire, que puis-je faire", {"entities": [("bac", "NIVEAU"), ("littéraire", "FILIERE")], "intent": "recherche_formation" }),
("voici mon parcours, aide-moi à m’orienter", {"entities": [], "intent": "recherche_formation" }),
("quelle est la différence entre une école privée et la fac", {"entities": [], "intent": "comparaison" }),
("je cherche une formation en droit", {"entities": [("droit", "DOMAINE")], "intent": "recherche_formation"}),
("Qu’est-ce que la cybersécurité exactement ?", {"entities": [("cybersécurité", "DOMAINE")], "intent": "clarification"}),
("je veux faire une licence en informatique", {"entities": [("licence", "NIVEAU"), ("informatique", "DOMAINE")], "intent": "recherche_formation"}),
("J'AIME BIEN LE FOOTBALL ", {"entities": [("football", "DOMAINE")], "intent": "info"}),
("je n'ai pas assez d'argent pour étudier, je veux faire des petits jobs", {"entities": [], "intent": "recherche_emploi"}),
("je veux apprendre la couture", {"entities": [("couture", "DOMAINE")], "intent": "recherche_formation"}),
("qu’est-ce qui est mieux entre médecine et pharmacie", {"entities": [("médecine", "DOMAINE"), ("pharmacie", "DOMAINE")], "intent": "comparaison"}),
("compare licence et BTS", {"entities": [("licence", "NIVEAU"), ("BTS", "NIVEAU")], "intent": "comparaison"}),
("j’aime le football, que puis-je étudier", {"entities": [("football", "DOMAINE")], "intent": "recherche_formation"}),
("je suis passionné par la couture", {"entities": [("couture", "DOMAINE")], "intent": "info"}),
("j’adore la musique, quel métier me conviendrait", {"entities": [("musique", "DOMAINE")], "intent": "recherche_emploi"}),
("aide-moi à trouver un DOMAINE", {"entities": [], "intent": "recherche_formation"}),
("je cherche du travail sans diplôme", {"entities": [], "intent": "recherche_emploi"}),
("Qu’est-ce que le Big Data et à quoi ça sert ?", {"entities": [("Big data", "DOMAINE")], "intent": "recherche_info"}),
("quelle formation après un bac scientifique", {"entities": [("bac scientifique", "NIVEAU")], "intent": "recherche_formation"}),
("Qu’est-ce que le droit des affaires ?", {"entities": [("droit des affaires", "DOMAINE")], "intent": "recherche_info"}),
("Qu’est-ce que le développement web full stack ?", {"entities": [("développement web full stack", "DOMAINE")], "intent": "recherche_info"}),
("Peux-tu me dire la recette d’un gâteau au chocolat ?", {"entities": [], "intent": "hors_contexte"}),
("Je viens d'obtenir mon bac scientifique", {"entities": [("bac scientifique", "NIVEAU")], "intent": "info"}),
("je veux faire du big data", {"entities": [("big data", "DOMAINE")], "intent": "recherche_formation"}),
("Où puis je faire cette licence?", {"entities": [("licence", "NIVEAU")], "intent": "recherche_ecole"}),
("Que propose concrètement l'UL?", {"entities": [("UL", "ECOLE")], "intent": "recherche_ecole"}),
("et l'epl?", {"entities": [("epl", "ECOLE")], "intent": "recherche_ecole"}),
("conseille moi", {"entities": [], "intent": "recherche_formation"}),
("Comment intégrer l'epl ?", {"entities": [], "intent": "info_admission"}),
("les conditions d'admission", {"entities": [], "intent": "info_admission"}),
("Quelles autres universités propose la formation en big data", {"entities": [("big data", "DOMAINE")], "intent": "recherche_ecole"}),
("Quelles autres formations me propose tu?", {"entities": [], "intent": "recherche_formation"}),
("Bonjour", {"entities": [], "intent": "discussion"}),
("Hello", {"entities": [], "intent": "discussion"}),
("Salut comment ça va ?", {"entities": [], "intent": "discussion"}),
]